Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Models/Campeonato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo004.Web.MVC.Models
{
    public class Campeonato
    {

        public int CampeonatoId { get; set; }

        public string Nome { get; set; }

        public int Duracao { get; set; }


        // Relacionamento Muitos para Muitos TIME
        public List<Time> TIME { get; set; }
    }
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo004.Web.MVC.Models
{
    public class Jogador
    {
        public int JogadorId { get; set; }

        [Required(ErrorMessage ="Informe o nome do Jogador")]
        public string Nome { get; set; }

        [Range(1, 99)]
        public int Numero { get; set; }

        //Relacionamento Time Jogador Muitos para um com Times
        
        public Time Time { get; set; }

        public int TimeId { get; set; }
    }
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Models/Tecnico.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo004.Web.MVC.Models
{
    public class Tecnico
    {

        public int TecnicoId { get; set; }


        [Display(Name = "Nome do Técnico")]
        public string Nome { get; set; }

        public decimal Salario { get; set; }
    }
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Models/Time.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo004.Web.MVC.Models
{
    public class Time
    {

        public int TimeId { get; set; }

        public string Nome { get; set; }

        [Display(Name = "Data da Fundação")]
        public DateTime DataFundacao { get; set; }

        //Relacionamento Time Tecnico um um 
        public Tecnico Tecnico { get; set; }
        public int TecnicoId { get; set; }


        // Relacionameno Time Jogador - Muitos para um com jogadores

        public List<Jogador> Jogadores { get; set; }


        // Relacionamento Muitos para Muitos com Campeonato
        public List<Campeonato> Campeonato { get; set; }
    }
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Controllers/JogadorController.cs
using Fiap.Exemplo004.Web.MVC.Models;
using Fiap.Exemplo004.Web.MVC.Persistencia;
using Fiap.Exemplo004.Web.MVC.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo004.Web.MVC.Controllers
{
    public class JogadorController : Controller
    {
        //private FutebolContext _context = new FutebolContext();

       private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            //Busca todos os times
            var lista = _unit.TimeRepository.Listar();
            ViewBag.times = new SelectList(lista,"Timeid","Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Jogador jogador) {

            if (ModelState.IsValid)
            {
                _unit.JogadorRepository.Cadastrar(jogador);
                _unit.Salvar();
                TempData["msg"] = "Jogador Cadastrado";
                return RedirectToAction("Cadastrar");
            }
            else
            {
                //Busca todos os times
                var lista = _unit.TimeRepository.Listar();
                ViewBag.times = new SelectList(lista, "Timeid", "Nome");
                return View(jogador);
            }
            

        }

        [HttpGet]
        public ActionResult Listar() {

            return View(_unit.JogadorRepository.Listar());
        }

       
    }
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Controllers/TimeController.cs
using Fiap.Exemplo004.Web.MVC.Models;
using Fiap.Exemplo004.Web.MVC.Persistencia;
using Fiap.Exemplo004.Web.MVC.Units;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo004.Web.MVC.Controllers
{
    public class TimeController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        // GET: Time
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Cadastrar() {

            return View();

        }

        [HttpPost]
        public ActionResult Cadastrar(Time time) {
            _unit.TimeRepository.Cadastrar(time);
            _unit.Salvar();
            TempData["msg"] = "Time cadastrado com Sucesso";
            return RedirectToAction("listar");

        }

        [HttpGet]
        public ActionResult Listar() {


            //Importante sempre quando tiver relacionamento adicionar o include para adicionar outras classes.
            return View(_unit.TimeRepository.Listar());
        }

        //Imporante Liberar o recurso após o uso.
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }


    }
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Views/Jogador/Cadastrar.cshtml
@model Fiap.Exemplo004.Web.MVC.Models.Jogador
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Jogador</h2>
@if (TempData["msg"] != null)
{

    <div class="alert alert-success">@TempData["msg"]</div>
}


@using (Html.BeginForm()) {

    <div class="from-group">
        @Html.LabelFor(j=>j.Nome)
        @Html.TextBoxFor(j=>j.Nome,new { @class="form-control"})
        @Html.ValidationMessageFor(j => j.Nome,
                        null, new { @class = "text-danger" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(j=>j.Numero)
        @Html.TextBoxFor(j=>j.Numero, new { @class="form-control"})
        @Html.ValidationMessageFor(J => J.Numero,
                        null, new { @class="text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(j=>j.Time)
        @Html.DropDownListFor(j=>j.TimeId ,
        ViewBag.times as SelectList,
        "Selecione",
        new { @class="form-control"})
        @Html.ValidationMessageFor(j => j.TimeId,
                        null, new { @class = "text-danger" })


    </div>

    <input type="submit" value="Salvar" class="btn btn-primary" />
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Views/Jogador/Listar.cshtml
@model List<Fiap.Exemplo004.Web.MVC.Models.Jogador>
@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Jogadores</h2>

@if (TempData["msg"] != null) {
    <div class="alert-success">

    @TempData["msg"]
    </div>
}

@using (Html.BeginForm()) {


<table class="table">
    <tr>
        <th>Nome</th>
        <th>Número</th>
        <th>Time</th>
    </tr>

    @foreach (var item in Model)
    {

    <tr>
        <td>@item.Nome</td>
        <td>@item.Numero</td>
        <td>@item.Time.Nome</td>

    </tr>
    }

</table>
}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
       
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.ActionLink("Fiap", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Cadastro Time", "Cadastrar", "Time")</li>
                                <li>@Html.ActionLink("Lista de Time", "Listar", "Time")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jogador<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Cadastro Jogador", "Cadastrar", "Jogador")</li>
                                <li>@Html.ActionLink("Lista de Jogadores", "Listar", "Jogador")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Views/Time/Cadastrar.cshtml
@model Fiap.Exemplo004.Web.MVC.Models.Time
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Time</h2>

@using (Html.BeginForm()) {

    <div class="form-group">
        @Html.LabelFor(a=>a.Nome)
        @Html.TextBoxFor(a=>a.Nome, new { @class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a=>a.DataFundacao)
        @Html.TextBoxFor(a=>a.DataFundacao, new { @class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a=>a.Tecnico.Nome)
        @Html.TextBoxFor(a=>a.Tecnico.Nome, new { @class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a=>a.Tecnico.Salario)
        @Html.TextBoxFor(a=>a.Tecnico.Salario, new { @class="form-control"})
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-default" />

}

Fiap.Exemplo004.Web.MVC/Fiap.Exemplo004.Web.MVC/Views/Time/Listar.cshtml
@model List<Fiap.Exemplo004.Web.MVC.Models.Time>
@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Times</h2>

@if (TempData["msg"] != null) {

    <div class="alert-success">@TempData["msg"]</div>

}


@using (Html.BeginForm()) {

<table class="table">

    <tr>
        <th>Nome</th>
        <th>Data de Fundação</th>
        <th>Técnico</th>
        <th>Salário</th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>@item.Nome</td>
        <td>@item.DataFundacao.ToShortDateString()</td>
        <td>@item.Tecnico.Nome</td>
        <td>@item.Tecnico.Salario</td>
    </tr>
    }


</table>

}