Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Models/Aposta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo03.Web.MVC.Models
{
    public class Aposta
    {
        public int id { get; set; }

        public decimal Valor { get; set; }

        public bool Acumulado { get; set; }

        public DateTime DataAposta { get; set; }
    }
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Models/Apostador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlTypes;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo03.Web.MVC.Models
{
    public class Apostador
    {
        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]
        [MinLength(5)]
        public string Email { get; set; }

        [Display(Name ="Data de Nascimento")]
        public DateTime DataNascimento { get; set; }

        [Required]
        [Column("SaldoTotal")]
        public decimal Saldo { get; set; }
    }
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Controllers/ApostaController.cs
using Fiap.Exemplo03.Web.MVC.Models;
using Fiap.Exemplo03.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo03.Web.MVC.Controllers
{
    public class ApostaController : Controller
    {

        private LoteriaContext _context = new LoteriaContext();
        // GET: Aposta
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro() {

            return View();
        }
        [HttpPost]
        public ActionResult Cadastro(Aposta aposta )
        {
            _context.Apostas.Add(aposta);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado com Sucesso";

            return RedirectToAction("listar");
        }

        [HttpGet]
        public ActionResult Listar()
        {

            return View(_context.Apostas.ToList());
        }

        [HttpGet]
        public ActionResult Alterar(int id) {

            return View(_context.Apostas.Find(id));

        }

        [HttpPost]
        public ActionResult Alterar(Aposta aposta) {
            _context.Entry(aposta).State = EntityState.Modified;
            _context.SaveChanges();
            TempData["msg"] = "Alterado com sucesso";
            return RedirectToAction("listar");

        }
        [HttpGet]
        public ActionResult Remover(int id) {

            var temp = _context.Apostas.Find(id);
            _context.Apostas.Remove(temp);
            _context.SaveChanges();
            TempData["msg"] = "Removido com Sucesso";
            return RedirectToAction("listar");
        }
    }
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Controllers/ApostadorController.cs
using Fiap.Exemplo03.Web.MVC.Models;
using Fiap.Exemplo03.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo03.Web.MVC.Controllers
{
    public class ApostadorController : Controller
    {
        private LoteriaContext _context = new LoteriaContext();

        [HttpGet]
        public ActionResult Remover(int id)
        {
            var apostador = _context.Apostadores.Find(id);
            _context.Apostadores.Remove(apostador);
            _context.SaveChanges();
            TempData["msg"] = "Removido";
            return RedirectToAction("Listar");
        }

        //Alterar com base no Id
        [HttpGet]
        public ActionResult Alterar(int id)

        {
            //Está devolvendo todo Objeto
            return View(_context.Apostadores.Find(id));
        }

        //Alterar com Post
        [HttpPost]
        public ActionResult Alterar(Apostador apostador)
        {

            _context.Entry(apostador).State = EntityState.Modified;
            _context.SaveChanges();
            TempData["msg"] = "Atualizado com sucesso";
            return RedirectToAction("Listar");
        }

        // GET: Apostador
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Cadastro(Apostador apostador)
        {
          
            _context.Apostadores.Add(apostador);
            _context.SaveChanges();
            //Mensagem
            TempData["msg"] = "Cadastrado com Sucesso";
            ViewBag.mensagem = "Gravado";
            return RedirectToAction("Cadastro");
        }
        [HttpGet]
        public ActionResult Listar()
        {
            //var context = new LoteriaContext();
           //List<Apostador> lista = _context.Apostadores.ToList();
           
            return View(_context.Apostadores.ToList());
        }

    }
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Aposta/Alterar.cshtml
@model Fiap.Exemplo03.Web.MVC.Models.Aposta
@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar Apostas</h2>

@using (Html.BeginForm()) {


    <div class="form-group">
        @Html.LabelFor(a=>a.Valor)
        @Html.TextBoxFor(a=>a.Valor, new { @class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a=>a.DataAposta)
        @Html.TextBoxFor(a=>a.DataAposta, new {@class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a=>a.Acumulado ,new { @class = "form-control" })
        @Html.CheckBoxFor(a=>a.Acumulado)
    </div>
    
    <input type="submit" value="Alterar" , class="btn btn-default" />
    @Html.ActionLink("Cancelar","listar","Aposta",new { @class="btn btn-default"})
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Aposta/Cadastro.cshtml
@model Fiap.Exemplo03.Web.MVC.Models.Aposta
@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro de Apostas</h2>
@Ajuda.Message(TempData["msg"] as string, "info")

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(a => a.Valor)
        @Html.TextBoxFor(a => a.Valor, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(a =>a.DataAposta)
        @Html.TextBoxFor(a => a.DataAposta, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.CheckBoxFor(a => a.Acumulado)
        @Html.LabelFor(a =>a.Acumulado)
    </div>

    <input type="submit" value="Cadastrar" />
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Aposta/Listar.cshtml
@model  List<Fiap.Exemplo03.Web.MVC.Models.Aposta>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar de Apostas</h2>

@if (TempData["msg"] != null) {

<div class="=alert alert-success">
    @TempData["msg"]

</div>

}

<table class="table">
    <tr>
        <th>Valor</th>
        <th>Data Aposta</th>
        <th>Acumulado</th>
    </tr>

    @foreach (var item in Model)
    {

   
    <tr>
        <td>@item.Valor</td>
        <td>@item.DataAposta.ToShortDateString()</td>
        <td>@item.Acumulado</td>
        <td>@Html.ActionLink("Editar","Alterar",new {id =item.id})</td>
        <td>@Html.ActionLink("Exlcuir","Remover",new { id=item.id})</td>

    </tr>
    }


</table>

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Apostador/Alterar.cshtml
@model Fiap.Exemplo03.Web.MVC.Models.Apostador
@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar Apostador</h2>

@using (Html.BeginForm())

{
    <div class="form-group">
        @Html.LabelFor(a => a.Nome)
        @Html.TextBoxFor(a => a.Nome, new { @class ="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.Email)
        @Html.TextBoxFor(a => a.Email, new { @class="form-control"})

    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.DataNascimento)
        @Html.TextBoxFor(a => a.DataNascimento, new { @class = "form-control" })

    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.Saldo)
        @Html.TextBoxFor(a => a.Saldo, new { @class = "form-control" })

    </div>


    <input type="submit" value="Salvar" class="btn btn-default" />
   //Criar um bõtão de outra forma
     @Html.ActionLink("Cancelar", "Listar", "Apostador", new { @class="btn btn-default"})
}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Apostador/Cadastro.cshtml
@model Fiap.Exemplo03.Web.MVC.Models.Apostador
@{
    ViewBag.Title = "Cadastro de Apostadores";
}

<h2>Cadastro de Apostadores</h2>

@Ajuda.Message(TempData["msg"] as string, "info")

@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(p=> p.Nome)
        @Html.TextBoxFor(p=> p.Nome, new { @class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(p=> p.Email)
        @Html.TextBoxFor(p=>p.Email, new { @class="form-control"})

    </div>

    <div class="form-group">
        @Html.LabelFor(p=>p.DataNascimento)
        @Html.TextBoxFor(p=>p.DataNascimento, new { @class="form-control"})

    </div>

    <div class="form-group">
        @Html.LabelFor(p=>p.Saldo)
        @Html.TextBoxFor(p=>p.Saldo, new { @class="form-control"})
    </div>

    <input type="submit" value="Cadastrar" />

}

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Apostador/Listar.cshtml
@model List<Fiap.Exemplo03.Web.MVC.Models.Apostador>

@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Apostadores</h2>
@if (TempData["msg"] != null)

{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Data de Nascimento</th>
        <th>Saldo</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>@item.Nome</td>
            <td>@item.Email</td>
            <td>@item.DataNascimento.ToShortDateString()</td>
            <td>@item.Saldo</td>
            <td>@Html.ActionLink("Editar","Alterar",
               new { id =item.Id})</td>
            <td>@Html.ActionLink("Excluir","Remover",
               new { id = item.Id })</td>
            <td>
                @Html.ActionLink(" ", "Alterar"
                            , new { id = item.Id }
                            , new { @class = "glyphicon glyphicon-pencil btn btn-primary" })
            @Html.ActionLink(" ", "Remover",
                            new { id = item.Id }
                            , new { @class = "glyphicon glyphicon-trash btn btn-danger" })
        </td>
        </tr>
    }

</table>

Fiap.Exemplo03.Web.MVC/Fiap.Exemplo03.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p class="navbar-brand">Fiap</p>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Loteria<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Apostador", "Cadastro", "Apostador")</li>
                            <li>@Html.ActionLink("Lista de Apostadores", "Listar", "Apostador")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Aposta<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Aposta", "Cadastro", "Aposta")</li>
                            <li>@Html.ActionLink("Lista de Apostas", "Listar", "Aposta")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>